name       : marisa-trite
version    : 0.2.6
release    : 1
source     :
    - https://github.com/s-yata/marisa-trie/archive/refs/tags/v0.2.6.tar.gz : 1063a27c789e75afa2ee6f1716cc6a5486631dcfcb7f4d56d6485d2462e566de
license    : BSD-2-Clause
component  : programming.library
summary    : Matching Algorithm with Recursively Implemented StorAge.
description: |
    Matching Algorithm with Recursively Implemented StorAge (MARISA is a static and space-efficient trie data structure. And libmarisa is a C++ library to provide an implementation of MARISA. Also, the package of libmarisa contains a set of command line tools for building and operating a MARISA-based dictionary.)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
